import type { ContractSchemaName } from '../src/registry.js';

export const ids = {
  a: '018f1e2d-3c4b-7a69-8def-0123456789ab',
  b: '018f1e2d-3c4b-7a69-9def-0123456789ac',
  c: '018f1e2d-3c4b-7a69-adef-0123456789ad',
  d: '018f1e2d-3c4b-7a69-bdef-0123456789ae',
} as const;

export const now = '2026-08-28T12:00:00.000Z';
export const later = '2099-08-28T12:00:00.000Z';
export const sha = 'a'.repeat(64);
export const authTag = 'a'.repeat(43);

export const modelSelection = {
  provider: 'openai',
  modelId: 'gpt-test',
  reasoningLevel: 'medium',
} as const;

const provenance = { kind: 'user', createdAt: now };
const preflight = {
  intentId: ids.a,
  normalizedArguments: { query: 'cupcakes' },
  resolvedResources: [],
  effects: ['network-read'],
  risk: 'low',
  destinations: [],
  limits: { timeoutMs: 10_000, maximumOutputBytes: 1024, network: 'allowlisted' },
  approval: { required: false, allowedScopes: [], freshApprovalOnly: false },
  approvalDigest: sha,
  preparedAt: now,
  expiresAt: later,
};

export const validFixtures = {
  'app-settings': {
    schemaVersion: 1,
    theme: 'cupcake-light',
    followSystemTheme: false,
    reducedMotion: 'system',
    textScale: 1,
    defaultModel: modelSelection,
    developerMode: false,
    thoughtsAndDreams: false,
    proactiveSuggestions: false,
    sendShortcut: 'enter',
    telemetry: 'local-only',
    developerEventRetentionMs: 2_592_000_000,
    personality: {
      preset: 'balanced',
      warmth: 0.5,
      verbosity: 0.5,
      initiative: 0.5,
      playfulness: 0.2,
    },
    executionPolicy: {
      sandboxedCodeEnabled: true,
      unsandboxedCodeEnabled: false,
      networkDefault: 'denied',
      automaticTaskThresholdMs: 20_000,
    },
  },
  artifact: {
    id: ids.a,
    conversationId: ids.b,
    title: 'Release notes',
    kind: 'document',
    currentRevisionId: ids.c,
    createdAt: now,
    updatedAt: now,
  },
  'artifact-revision': {
    id: ids.c,
    artifactId: ids.a,
    contentObjectSha256: sha,
    mimeType: 'text/markdown',
    byteSize: 42,
    createdAt: now,
    provenance,
  },
  'broker-request': {
    protocol_version: 1,
    request_type: 'tool.preflight',
    payload: {
      intent: {
        invocation_id: 'invoke-1',
        run_id: 'run-1',
        tool_name: 'files.read',
        tool_version: '1.0.0',
        arguments: { grant_id: 'opaque-grant', relative_path: 'README.md' },
        project_id: null,
        task_id: null,
        requested_at: now,
      },
      descriptor: {
        name: 'files.read',
        version: '1.0.0',
        display_name: 'Read file',
        description: 'Read an approved file.',
        input_schema: { type: 'object' },
        output_schema: { type: 'object' },
        effects: ['read_files'],
        required_grants: ['filesystem.read'],
        default_data_flows: [
          {
            destination: 'local',
            destination_label: 'This device',
            categories: ['requested input'],
            purpose: 'Complete the tool action',
            contains_user_content: false,
          },
        ],
        timeout_seconds: 60,
        cancellable: true,
        category: 'native',
      },
    },
  },
  'broker-tool-result': {
    invocation_id: 'invoke-1',
    status: 'succeeded',
    output: { text: 'hello' },
    error_code: null,
    error_message: null,
    artifacts: [],
    started_at: now,
    finished_at: now,
  },
  context: {
    conversationId: ids.a,
    model: modelSelection,
    items: [{ kind: 'file', id: ids.b, label: 'README.md', tokenCount: 80 }],
    totalTokens: 80,
    maximumTokens: 128_000,
    outboundDestination: { route: 'cloud', provider: 'openai', displayName: 'OpenAI' },
    compiledAt: now,
  },
  conversation: {
    id: ids.a,
    title: 'Welcome',
    activeBranchId: ids.b,
    createdAt: now,
    updatedAt: now,
    model: modelSelection,
  },
  'conversation-branch': {
    id: ids.b,
    conversationId: ids.a,
    headMessageId: null,
    createdAt: now,
  },
  persona: {
    id: ids.a,
    name: 'Mira',
    handle: 'mira',
    avatar: 'atlas:7',
    role: 'Research lead',
    description: 'Finds evidence.',
    instructions: '',
    speakWhen: 'Research would help.',
    personality: { preset: 'balanced', warmth: 0.5, brevity: 0.5, initiative: 0.7 },
    modelId: 'mock:cupcake-deterministic',
    createdAt: now,
    updatedAt: now,
    archivedAt: null,
  },
  'conversation-participant': {
    id: ids.b,
    conversationId: ids.a,
    personaId: ids.a,
    position: 0,
    enabled: true,
    isLead: true,
    addedAt: now,
    persona: {
      id: ids.a,
      name: 'Mira',
      handle: 'mira',
      avatar: 'atlas:7',
      role: 'Research lead',
      description: 'Finds evidence.',
      instructions: '',
      speakWhen: 'Research would help.',
      personality: { preset: 'balanced', warmth: 0.5, brevity: 0.5, initiative: 0.7 },
      modelId: 'mock:cupcake-deterministic',
      createdAt: now,
      updatedAt: now,
      archivedAt: null,
    },
    availability: { status: 'ready', message: '' },
  },
  'group-turn-preflight': {
    turnId: ids.d,
    planRevision: sha,
    digest: sha,
    rosterRevision: 1,
    headMessageId: null,
    userMessageId: null,
    mode: 'smart',
    strategy: 'smart-selective',
    maxReplies: 2,
    maxSelectorCalls: 2,
    selectorMaxOutputTokens: 256,
    selector: null,
    eligibleSpeakers: [],
    ineligibleSpeakers: [],
    sendable: true,
    confirmationRequired: false,
    confirmationToken: null,
    expiresAt: later,
    disclosure: {
      selector: null,
      candidateRoutes: [],
      ineligibleRoutes: [],
      maxSelectorCalls: 2,
      selectorMaxOutputTokens: 256,
      maxReplies: 2,
    },
  },
  'group-turn': {
    turnId: ids.d,
    conversationId: ids.a,
    branchId: ids.b,
    userMessageId: ids.c,
    status: 'completed',
    mode: 'smart',
    digest: sha,
    planRevision: sha,
    rosterRevision: 1,
    maxReplies: 2,
    maxSelectorCalls: 2,
    selectorCalls: 1,
    responderCalls: 1,
    selectorUsage: [],
    plan: {
      conversationId: ids.a,
      branchId: ids.b,
      headMessageId: null,
      projectId: null,
      rosterRevision: 1,
      strategy: 'smart-selective',
      mode: 'smart',
      mentions: [],
      selector: null,
      eligibleSpeakers: [],
      ineligibleSpeakers: [],
      maxReplies: 2,
      maxSelectorCalls: 2,
      selectorMaxOutputTokens: 256,
      effectiveOffline: false,
      contentSha256: sha,
      attachmentBindings: [],
      referenceBindings: [],
      memoryIds: [],
      toolIds: [],
      maxOutputTokens: null,
    },
    createdAt: now,
    updatedAt: now,
    completedAt: now,
    members: [],
  },
  file: {
    id: ids.a,
    displayName: 'README.md',
    sourceHandle: 'grant:file:1',
    mimeType: 'text/markdown',
    byteSize: 100,
    contentSha256: sha,
    modifiedAt: now,
    destination: 'local',
    ingestion: { state: 'indexed', indexedAt: now, chunkCount: 1 },
    provenance,
  },
  memory: {
    id: ids.a,
    kind: 'preference',
    scope: { kind: 'global' },
    content: 'Prefer concise prose.',
    status: 'active',
    sensitivity: 'ordinary',
    confidence: 1,
    explicit: true,
    revisionId: ids.b,
    evidence: [],
    provenance,
    createdAt: now,
    updatedAt: now,
  },
  'memory-mutation': {
    action: 'confirm-candidate',
    memoryId: ids.a,
    expectedRevisionId: ids.b,
    decidedAt: now,
  },
  message: {
    id: ids.a,
    conversationId: ids.b,
    branchId: ids.c,
    role: 'assistant',
    status: 'completed',
    content: [{ type: 'text', text: 'Hello.' }],
    createdAt: now,
    completedAt: now,
    model: modelSelection,
  },
  model: {
    id: 'gpt-test',
    provider: 'openai',
    family: 'gpt-test',
    displayName: 'GPT Test',
    capabilities: {
      streaming: true,
      toolCalling: true,
      structuredOutput: true,
      imageInput: true,
      documentInput: true,
      webSearch: true,
      citations: true,
      reasoning: true,
      embeddings: false,
    },
    reasoningLevels: ['none', 'medium'],
    contextWindowTokens: 128_000,
    maximumOutputTokens: 16_384,
    privacyRoute: 'direct-cloud',
    speedClass: 'balanced',
    costClass: 'medium',
    lifecycle: 'available',
  },
  project: {
    id: ids.a,
    name: 'CUPCAKEAGI',
    createdAt: now,
    updatedAt: now,
    rootHandles: ['grant:directory:1'],
    readOnlyByDefault: true,
  },
  protocol: {
    version: 1,
    messageId: ids.a,
    correlationId: ids.b,
    sessionId: ids.c,
    sequence: 1,
    deadline: later,
    lineage: {},
    type: 'request',
    payload: { method: 'models.list' },
    authTag,
  },
  provider: {
    id: 'openai',
    displayName: 'OpenAI',
    privacyRoute: 'direct-cloud',
    authentication: 'api-key',
    endpoint: 'https://api.openai.com/v1',
    health: { state: 'unknown' },
    credentialState: 'configured',
  },
  'run-event': {
    id: ids.a,
    runId: ids.b,
    conversationId: ids.c,
    branchId: ids.d,
    sequence: 1,
    occurredAt: now,
    visibility: 'user',
    event: { kind: 'message-delta', messageId: ids.a, delta: 'Hello' },
  },
  'search-request': {
    query: 'cupcake',
    kinds: ['conversation', 'artifact'],
    mode: 'hybrid',
    limit: 20,
  },
  'search-result': {
    kind: 'artifact',
    id: ids.a,
    title: 'Release notes',
    excerpt: 'CUPCAKEAGI 2.0',
    lexicalScore: 2.3,
    semanticScore: 0.9,
    updatedAt: now,
  },
  'task-command': { command: 'steer', taskId: ids.a, requestedAt: now, message: 'Focus on tests.' },
  task: {
    id: ids.a,
    runId: ids.b,
    conversationId: ids.c,
    branchId: ids.d,
    title: 'Index repository',
    state: 'running',
    promotionReason: 'repository-indexing',
    progress: { completedUnits: 2, totalUnits: 10 },
    checkpointVersion: '1',
    attempt: 1,
    maximumAttempts: 3,
    createdAt: now,
    startedAt: now,
  },
  theme: {
    id: 'cupcake-light',
    colors: {
      crumb: '#F6F2EB',
      paper: '#FFFCF7',
      cocoa: '#2A2322',
      berry: '#9F3E62',
      pistachio: '#5D724F',
      blueberry: '#536594',
    },
    typography: {
      display: 'Bricolage Grotesque',
      body: 'Atkinson Hyperlegible',
      mono: 'IBM Plex Mono',
    },
    mascotStyle: 'flat',
  },
  tool: {
    id: ids.a,
    stableName: 'web.search',
    version: '1.0.0',
    displayName: 'Web Search',
    description: 'Search the public web.',
    source: 'native',
    inputSchema: { type: 'object' },
    outputSchema: { type: 'object' },
    declaredEffects: ['network-read'],
    defaultRisk: 'low',
    requiresProject: false,
    available: true,
  },
  'tool-intent': {
    id: ids.a,
    descriptorName: 'web.search',
    descriptorVersion: '1.0.0',
    arguments: { query: 'cupcakes' },
    reason: 'Answer the user.',
    requestedAt: now,
  },
  'tool-preflight': preflight,
  'tool-result': {
    state: 'completed',
    intentId: ids.a,
    startedAt: now,
    finishedAt: now,
    durationMs: 10,
    output: { results: [] },
    outputBytes: 12,
    generatedResourceIds: [],
    provenance: {},
  },
} satisfies Record<ContractSchemaName, unknown>;
