import type { Conversation, MemoryRecord, ModelDescriptor, Task, ToolDescriptor } from './types';

export const conversations: Conversation[] = [
  {
    id: 'chat-1',
    title: 'Architecture review',
    preview: 'The boundary between the desktop shell and runtime is now…',
    updated: '8 min',
    project: 'Cupcake 2.0',
    pinned: true,
  },
  {
    id: 'chat-2',
    title: 'Local model shortlist',
    preview: 'Compare the 8B quantizations for a 12 GB card.',
    updated: 'Yesterday',
    project: 'Local lab',
    pinned: true,
    unread: true,
  },
  {
    id: 'chat-3',
    title: 'Field notes synthesis',
    preview: 'Turn these interviews into themes and supporting evidence.',
    updated: 'Tue',
    project: 'Atlas research',
  },
  {
    id: 'chat-4',
    title: 'A small question about SQLite',
    preview: 'Why is WAL a better fit for this workload?',
    updated: 'Aug 24',
  },
  {
    id: 'chat-5',
    title: 'Release checklist',
    preview: 'Keep this local until the installer has been tested.',
    updated: 'Aug 20',
    project: 'Cupcake 2.0',
  },
];

export const tasks: Task[] = [
  {
    id: 'task-1',
    title: 'Repository redesign',
    detail: 'Reading the desktop architecture and preparing an evidence-backed redesign.',
    status: 'working',
    progress: 68,
    project: 'Cupcake 2.0',
    elapsed: '12m 41s',
    steps: [
      { label: 'Map application boundaries', state: 'complete' },
      { label: 'Read 34 source files', state: 'complete' },
      { label: 'Compare persistence options', state: 'active' },
      { label: 'Draft architecture artifact', state: 'queued' },
      { label: 'Review findings', state: 'queued' },
    ],
  },
  {
    id: 'task-2',
    title: 'Index Atlas interviews',
    detail: 'Extracting people, themes, and stable source locators.',
    status: 'waiting',
    progress: 44,
    project: 'Atlas research',
    elapsed: '7m 09s',
    steps: [
      { label: 'Parse recordings', state: 'complete' },
      { label: 'Waiting for folder access', state: 'active' },
      { label: 'Build search index', state: 'queued' },
    ],
  },
  {
    id: 'task-3',
    title: 'Local runtime benchmark',
    detail: 'Measured three quantizations against the same prompt set.',
    status: 'complete',
    progress: 100,
    project: 'Local lab',
    elapsed: '28m 18s',
    steps: [
      { label: 'Warm model', state: 'complete' },
      { label: 'Run prompt set', state: 'complete' },
      { label: 'Save results', state: 'complete' },
    ],
  },
  {
    id: 'task-4',
    title: 'Import damaged interview archive',
    detail: 'Stopped safely because three source files could not be decoded.',
    status: 'failed',
    progress: 18,
    project: 'Atlas research',
    elapsed: '1m 44s',
    steps: [
      { label: 'Inspect archive', state: 'complete' },
      { label: 'Decode recordings', state: 'failed' },
      { label: 'Build source map', state: 'queued' },
    ],
  },
];

export const memories: MemoryRecord[] = [
  {
    id: 'mem-1',
    type: 'Preference',
    title: 'Writing style',
    body: 'Prefers concise technical writing with concrete examples and no ceremonial preamble.',
    scope: 'About me',
    source: 'Corrected in “Release checklist”',
    confidence: 0.96,
    enabled: true,
    pinned: true,
  },
  {
    id: 'mem-2',
    type: 'Instruction',
    title: 'Release boundary',
    body: 'Do not push or publish Cupcake Chat until the local release candidate is reviewed.',
    scope: 'Cupcake 2.0',
    source: 'Explicit instruction · Aug 28',
    confidence: 1,
    enabled: true,
    pinned: true,
  },
  {
    id: 'mem-3',
    type: 'Decision',
    title: 'Model selection',
    body: 'Model choice stays explicit. Automatic model routing is out of scope.',
    scope: 'Cupcake 2.0',
    source: 'Architecture review',
    confidence: 1,
    enabled: true,
  },
  {
    id: 'mem-4',
    type: 'Fact',
    title: 'Local graphics card',
    body: 'Primary local-model machine has approximately 12 GB of VRAM.',
    scope: 'Local lab',
    source: 'Local model shortlist',
    confidence: 0.92,
    enabled: true,
  },
  {
    id: 'mem-5',
    type: 'Temporary',
    title: 'Benchmark prompt set',
    body: 'Use the 24-prompt coding and document-analysis fixture until the current comparison is complete.',
    scope: 'Local lab',
    source: 'Task state',
    confidence: 0.88,
    enabled: true,
    expires: 'in 6 days',
  },
];

export const models: ModelDescriptor[] = [
  {
    id: 'gpt',
    runtimeModelId: 'openai:gpt-6-astra',
    provider: 'OpenAI',
    name: 'GPT-6 Astra',
    route: 'Cloud',
    tags: ['Reasoning', 'Vision', 'Tools', 'Coding'],
    context: '1.05m',
    cost: '$$$',
    status: 'ready',
    description: 'Catalog-backed default for general reasoning and agent work.',
    selected: true,
  },
  {
    id: 'claude',
    runtimeModelId: 'anthropic:claude-sonnet-5',
    provider: 'Anthropic',
    name: 'Claude Sonnet 5',
    route: 'Cloud',
    tags: ['Reasoning', 'Vision', 'Coding'],
    context: '1m',
    cost: '$$',
    status: 'setup',
    description: 'Deep analysis and careful long-form work.',
  },
  {
    id: 'gemini',
    runtimeModelId: 'google:gemini-3.8-flash',
    provider: 'Google',
    name: 'Gemini 3.8 Flash',
    route: 'Cloud',
    tags: ['Vision', 'Long context', 'Fast'],
    context: '1m',
    cost: '$$',
    status: 'setup',
    description: 'Broad multimodal context and fast synthesis.',
  },
  {
    id: 'grok',
    runtimeModelId: 'xai:grok-4.6',
    provider: 'xAI',
    name: 'Grok 4.6',
    route: 'Cloud',
    tags: ['Reasoning', 'Tools'],
    context: '500k',
    cost: '$$',
    status: 'setup',
    description: 'Reasoning and current-information workloads.',
  },
  {
    id: 'mistral',
    runtimeModelId: 'mistral:mistral-medium-3-5',
    provider: 'Mistral',
    name: 'Mistral Medium 3.5',
    route: 'Cloud',
    tags: ['Fast', 'Coding', 'Tools'],
    context: '256k',
    cost: '$',
    status: 'setup',
    description: 'Efficient multilingual and code work.',
  },
  {
    id: 'cohere',
    runtimeModelId: 'cohere:command-a-plus-05-2026',
    provider: 'Cohere',
    name: 'Command A Plus',
    route: 'Cloud',
    tags: ['Tools', 'Retrieval', 'Fast'],
    context: '128k',
    cost: 'Check provider',
    status: 'setup',
    description: 'Enterprise chat and tool workflows through the packaged text route.',
  },
  {
    id: 'nim-nemotron',
    runtimeModelId: 'nvidia-nim:nvidia/llama-3.1-nemotron-ultra-253b-v1',
    provider: 'NVIDIA NIM',
    name: 'Llama 3.1 Nemotron Ultra 253B',
    route: 'Cloud',
    tags: ['Reasoning', 'Tools', 'NVIDIA'],
    context: '131k',
    cost: 'NVIDIA pricing',
    status: 'setup',
    description: 'NVIDIA-hosted reasoning model discovered through the live NIM catalog.',
  },
  {
    id: 'nim-llama',
    runtimeModelId: 'nvidia-nim:meta/llama-3.1-70b-instruct',
    provider: 'NVIDIA NIM',
    name: 'Llama 3.1 70B Instruct',
    route: 'Cloud',
    tags: ['General', 'Tools', 'NVIDIA'],
    context: '128k',
    cost: 'NVIDIA pricing',
    status: 'setup',
    description: 'General chat and tool route surfaced by NVIDIA NIM model discovery.',
  },
  {
    id: 'nim-deepseek',
    runtimeModelId: 'nvidia-nim:deepseek-ai/deepseek-r1',
    provider: 'NVIDIA NIM',
    name: 'DeepSeek R1',
    route: 'Cloud',
    tags: ['Reasoning', 'Math', 'NVIDIA'],
    context: 'See provider',
    cost: 'NVIDIA pricing',
    status: 'setup',
    description: 'Reasoning route listed by NVIDIA NIM; live availability is verified on connect.',
  },
  {
    id: 'qwen',
    runtimeModelId: 'cupcake-local:qwen3-8b-q4-k-m',
    provider: 'Cupcake Local',
    name: 'Qwen3 8B · Q4_K_M',
    route: 'Local',
    tags: ['Coding', 'Private'],
    context: '131k',
    cost: 'Free',
    status: 'catalog',
    description: 'Strong general-purpose 8B model with a practical memory footprint.',
    source: 'Cupcake verified catalog',
    license: 'Apache-2.0',
    parameters: '8B',
    quantization: 'Q4_K_M',
    fileSizeBytes: 5_027_783_488,
    estimatedRamBytes: 7_300_000_000,
    estimatedVramBytes: 6_200_000_000,
    estimatedDiskBytes: 5_630_000_000,
    speedClass: 'Responsive',
  },
  {
    id: 'qwen-4b',
    runtimeModelId: 'cupcake-local:qwen3-4b-q4-k-m',
    provider: 'Cupcake Local',
    name: 'Qwen3 4B · Q4_K_M',
    route: 'Local',
    tags: ['Reasoning', 'Multilingual', 'Coding', 'Private'],
    context: '131k',
    cost: 'Free',
    status: 'catalog',
    description: 'Compact multilingual reasoning and chat model from the signed local catalog.',
    source: 'Cupcake verified catalog',
    license: 'Apache-2.0',
    parameters: '4B',
    quantization: 'Q4_K_M',
    fileSizeBytes: 2_497_280_640,
    estimatedRamBytes: 4_100_000_000,
    estimatedVramBytes: 3_200_000_000,
    estimatedDiskBytes: 2_797_000_000,
    speedClass: 'Fast',
  },
  {
    id: 'qwen-14b',
    runtimeModelId: 'cupcake-local:qwen3-14b-q4-k-m',
    provider: 'Cupcake Local',
    name: 'Qwen3 14B · Q4_K_M',
    route: 'Local',
    tags: ['Reasoning', 'Private', 'Hybrid'],
    context: '131k',
    cost: 'Free',
    status: 'catalog',
    description: 'Higher-capacity local reasoning model for machines with spare headroom.',
    source: 'Cupcake verified catalog',
    license: 'Apache-2.0',
    parameters: '14B',
    quantization: 'Q4_K_M',
    fileSizeBytes: 9_001_752_960,
    estimatedRamBytes: 12_600_000_000,
    estimatedVramBytes: 10_800_000_000,
    estimatedDiskBytes: 10_082_000_000,
    speedClass: 'Measured after install',
  },
];

export const tools: ToolDescriptor[] = [
  {
    id: 'files',
    name: 'Files & folders',
    description: 'Read approved files, search projects, and stage exact changes.',
    provider: 'Cupcake',
    route: 'Local',
    enabled: true,
    permissions: ['Read selected folders', 'Ask before writing'],
    lastUsed: '3 min ago',
    kind: 'native',
  },
  {
    id: 'web',
    name: 'Web research',
    description: 'Search and read public webpages with source citations.',
    provider: 'Cupcake',
    route: 'Cloud',
    enabled: true,
    permissions: ['Public internet'],
    lastUsed: '12 min ago',
    kind: 'native',
  },
  {
    id: 'python',
    name: 'Python workspace',
    description: 'Run bounded Python in a staged, network-free workspace.',
    provider: 'Cupcake',
    route: 'Local',
    enabled: true,
    permissions: ['Sandbox only', 'No network'],
    lastUsed: 'Yesterday',
    kind: 'native',
  },
  {
    id: 'git',
    name: 'Git',
    description: 'Inspect history and prepare patches without changing the repository.',
    provider: 'Cupcake',
    route: 'Local',
    enabled: true,
    permissions: ['Read repository', 'Ask before apply'],
    lastUsed: '8 min ago',
    kind: 'native',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Inspect repositories, issues, pull requests, and checks.',
    provider: 'MCP · GitHub',
    route: 'Cloud',
    enabled: true,
    permissions: ['Read repositories', 'Ask before external actions'],
    lastUsed: '2 days ago',
    kind: 'mcp',
  },
  {
    id: 'drive',
    name: 'Google Drive',
    description: 'Search and read files from selected Drive folders.',
    provider: 'MCP · Google',
    route: 'Cloud',
    enabled: false,
    permissions: ['Not connected'],
    lastUsed: 'Never',
    kind: 'mcp',
  },
  {
    id: 'calendar',
    name: 'Calendar',
    description: 'Review availability and create events after approval.',
    provider: 'MCP · Google',
    route: 'Cloud',
    enabled: false,
    permissions: ['Not connected'],
    lastUsed: 'Never',
    kind: 'mcp',
  },
];

export const artifacts = [
  {
    id: 'a1',
    name: 'Cupcake Chat architecture.md',
    type: 'Document',
    updated: '2 min ago',
    revisions: 4,
    project: 'Cupcake 2.0',
    size: '18.4 KB',
  },
  {
    id: 'a2',
    name: 'local-model-benchmarks.csv',
    type: 'Table',
    updated: 'Yesterday',
    revisions: 2,
    project: 'Local lab',
    size: '7.2 KB',
  },
  {
    id: 'a3',
    name: 'research-map.mmd',
    type: 'Diagram',
    updated: 'Tue',
    revisions: 3,
    project: 'Atlas research',
    size: '3.1 KB',
  },
  {
    id: 'a4',
    name: 'provider-matrix.html',
    type: 'Webpage',
    updated: 'Aug 24',
    revisions: 1,
    project: 'Cupcake 2.0',
    size: '42.7 KB',
  },
];
